version: "3.2"

services:

  web:
    container_name: __name__-web
    working_dir: /app/web
    build:
      context: .docker
      dockerfile: Dockerfile.extension
    volumes:
      - .:/app

  backend:
    container_name: __name__-backend
    working_dir: /app/backend
    build:
      context: .docker
      dockerfile: Dockerfile.extension
    volumes:
      - ./:/app

  teletron:
    container_name: __name__-teletron
    build: .docker
    environment:
      - PORT=80
    volumes:
      - ./backend:/build:ro
      - .docker/config:/config
    ports:
      - 1115:80
