#!/bin/bash
set -e

echo "Building backend."
cd backend && npm run build
echo "Building web."
cd ../web && npm run build

cd ../backend && tar -cvzf "./extension-__name__.tar.gz" build package.json teletron.json package-lock.json && cd ..

echo "Build available at: backend/extension-__name__.tar.gz"
